# Generated by Django 6.0.3 on 2026-03-08 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodcloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlogentry',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
